name = "potlucky-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2024-01-01"

[vars]
POSTHOG_HOST = "https://eu.i.posthog.com"
POSTHOG_PROJECT_API_KEY = "phc_fg3D6jOSQxCrYRLoxoZx2X11FwgKoL5b0RSnJfdEnnV"
